version: '3'
services:
  container_app:
    container_name: container_app
    build:
      context: ./desafio1
    ports:
      
      8080:8080
    networks:
      mired

container_vue:
  container_name: container_vue
  build:
    context: ./vue_desafio1
  ports:
    8081:8080
  networks:
    mired